list: $/crydesign/funwiki/models/peoplepseudos/columns.yaml
modelClass: Crydesign\FunWiki\Models\PeoplePseudos
title: PeoplePseudos
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'crydesign/funwiki/peoplepseudos/update/:id'
