list: $/crydesign/funwiki/models/people/columns.yaml
modelClass: Crydesign\FunWiki\Models\People
title: Peoples
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'crydesign/funwiki/peoples/update/:id'
