plugin:
    name: 'crydesign.funwiki::lang.plugin.name'
    description: 'Backend fun-wiki.xyz site'
    author: CRYDEsigN
    icon: oc-icon-adn
    homepage: ''
navigation:
    fun-wiki:
        label: 'crydesign.funwiki::lang.plugin.name'
        url: crydesign/funwiki/news
        icon: plugins/crydesign/funwiki/assets/images/logo.png
        iconSvg: plugins/crydesign/funwiki/assets/images/logo.png
        order: 700
        sideMenu:
            Peoples:
                label: Люди
                url: crydesign/funwiki/peoples
                icon: icon-users
                group: Персоналии
            PeopleRoles:
                label: 'Вид деятельности'
                url: crydesign/funwiki/peopleroles
                icon: icon-list-ul
                group: Справочники
            side-menu-item:
                label: 'Menu Item'
                url: crydesign/funwiki/books
                icon: icon-sitemap
