plugin:
    name: 'crydesign.funwiki::lang.plugin.name'
    description: 'crydesign.funwiki::lang.plugin.description'
    author: CRYDEsigN
    icon: oc-icon-certificate
    homepage: ''
navigation:
    fun-wiki:
        label: 'crydesign.funwiki::lang.plugin.name'
        url: crydesign/funwiki/news
        icon: icon-adn
        sideMenu:
            side-menu-item:
                label: News
                url: crydesign/funwiki/news
                icon: icon-sitemap
            news-type:
                label: 'News Type'
                url: crydesign/funwiki/newstype
                icon: icon-sitemap
            universes:
                label: Вселенные
                url: crydesign/funwiki/universes
                icon: icon-renren
            genres:
                label: Жанры
                url: crydesign/funwiki/genres
                icon: icon-tags
            moviesgenre:
                label: 'Жанры фильмов'
                url: crydesign/funwiki/moviesgenre
                icon: icon-file-movie-o
            book:
                label: Книги
                url: crydesign/funwiki/books
                icon: icon-book
            personroles:
                label: 'Person Roles'
                url: crydesign/funwiki/personroles
                icon: icon-users
            persons:
                label: Persons
                url: crydesign/funwiki/persons
                icon: icon-user
