list: $/crydesign/funwiki/models/newstype/columns.yaml
modelClass: Crydesign\FunWiki\Models\NewsType
title: NewsType
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'crydesign/funwiki/newstype/update/:id'
