person_id:
    label: Person_id
    view:
        list: $/crydesign/funwiki/models/person/columns1.yaml
        toolbarButtons: add|remove
    manage:
        list: $/crydesign/funwiki/models/person/columns1.yaml
        form: $/crydesign/funwiki/models/person/fields1.yaml
        