title: Persons
modelClass: Crydesign\FunWiki\Models\Person
list: $/crydesign/funwiki/models/person/columns.yaml
recordUrl: 'crydesign/funwiki/persons/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
showSorting: 1
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
showTree: 1
treeExpanded: 1
