list: $/crydesign/funwiki/models/personroles/columns.yaml
modelClass: Crydesign\FunWiki\Models\PersonRoles
title: PersonRoles
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'crydesign/funwiki/personroles/update/:id'
