list: $/crydesign/funwiki/models/universe/columns.yaml
modelClass: Crydesign\FunWiki\Models\Universe
title: Universes
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'crydesign/funwiki/universes/update/:id'
