list: $/crydesign/funwiki/models/news/columns.yaml
modelClass: Crydesign\FunWiki\Models\News
title: News
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'crydesign/funwiki/news/update/:id'
