list: $/crydesign/funwiki/models/moviesgenre/columns.yaml
modelClass: Crydesign\FunWiki\Models\MoviesGenre
title: MoviesGenre
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'crydesign/funwiki/moviesgenre/update/:id'
